FROM node:14.14.0-alpine

USER node
RUN mkdir /home/node/my-express-server
WORKDIR /home/node/my-express-server

COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

CMD ["npm", "run", "dev"]